#!/usr/bin/env bash
#Run Nginx as Nginx
pkill -f apache2
sudo sed -i "s|#user www-data|user nginx|g" /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx start
