#!/usr/bin/env bash
#Bash script that configures Nginx server so that /redirect_me is redirecting to another page
sudo apt update
sudo apt install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://alu-intranet.hbtn.io/ permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
